### ISSUE TITLE
package.json contains wrong version number

### ISSUE THREAD

**Issue by joliebig** [gsdlab/ClaferMooVisualizer#19]
During the installation of clafermoovisualizer according to the install instructions mentioned here [(link)](https://github.com/gsdlab/ClaferMooVisualizer), I was not able to perform the step `node install` successfully because the version number in `package.json` [(link)](https://github.com/gsdlab/ClaferMooVisualizer/blob/master/Server/package.json) was wrong. After changing from `0.3.6.1` to `0.3.6` the `node install` worked.

`node -version` => v0.12.7

**Comment by mantkiew** [comment]
We're on 0.4.1 version now, so the issue is resolved.
