### ISSUE TITLE
Reference to not existing start script in configuration file

### ISSUE THREAD

**Issue by joliebig** [gsdlab/ClaferMooVisualizer#20]
The configuration file `backends.json` contains an outdated reference to a start script [link](https://github.com/gsdlab/ClaferMooVisualizer/blob/master/Server/Backends/backends.json#L9). The script `claferChocoIG.sh` does not exist. Should be fixed as in [link](https://github.com/gsdlab/ClaferIDE/blob/d372b2ff82cd8931849fa1fd8fe48ba527ac9c84/Server/Backends/backends.json#L36).

**Comment by mantkiew** [comment]
fixed, using 

```
java ~/bin/claferchocoig.jar
```
by default.
