### ISSUE TITLE
wrong scale of spider-graph visualization

### ISSUE THREAD

**Issue by joliebig** [gsdlab/ClaferMooVisualizer#22]
Hi,
in tried the mobile-phone example (5 objectives) with the new release 0.4.1. I noticed that the visualization is not scaled right (see example below). This did not occur in the previous stable release of ClaferMooVisualizer.

![image](https://cloud.githubusercontent.com/assets/380818/10011880/66561f8a-6101-11e5-872b-677295f2fd67.png)

thanks in advance
joliebig

**Comment by mantkiew** [comment]
Fixed in [commit](https://github.com/gsdlab/ClaferMooVisualizer/commit/2afdc73ff191a64dcfaf1923502a74637b893b1a). I've just updated the server and it works well now.
